# Generated by Django 5.1.2 on 2024-10-26 21:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("domain_name", "Domain Name"),
                            ("domain_name_holding", "Domain Name Holding"),
                            ("general_merchandise", "General Merchandise"),
                            ("milestone", "Milestone"),
                            ("motor_vehicle", "Motor Vehicle"),
                            ("broker_fee", "Broker Fee"),
                            ("partner_fee", "Partner Fee"),
                            ("shipping_fee", "Shipping Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inspection_period", models.IntegerField(default=259200)),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("merchant_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("usd", "USD"),
                            ("aud", "AUD"),
                            ("euro", "EURO"),
                            ("gbp", "GBP"),
                            ("cad", "CAD"),
                        ],
                        default="usd",
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DisbursementMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("savings", "Savings"), ("checking", "Checking")],
                        max_length=20,
                    ),
                ),
                ("bank_aba_routing_number", models.CharField(max_length=20)),
                ("bank_account_number", models.CharField(max_length=20)),
                ("bank_name", models.CharField(max_length=100)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("usd", "US Dollar"),
                            ("eur", "Euro"),
                            ("gbp", "British Pound"),
                            ("jpy", "Japanese Yen"),
                            ("chf", "Swiss Franc"),
                            ("aud", "Australian Dollar"),
                            ("cad", "Canadian Dollar"),
                            ("cny", "Chinese Renminbi"),
                            ("hkd", "Hong Kong Dollar"),
                            ("inr", "Indian Rupee"),
                            ("krw", "South Korean Won"),
                            ("mxn", "Mexican Peso"),
                            ("nzd", "New Zealand Dollar"),
                            ("rub", "Russian Ruble"),
                            ("sgd", "Singapore Dollar"),
                            ("zar   ", "South African Rand"),
                        ],
                        max_length=6,
                    ),
                ),
                ("type", models.CharField(default="ach", max_length=20)),
                (
                    "bank_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escrowapp.bankaddress",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EscrowCustomer",
            fields=[
                (
                    "customer_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("address_line1", models.CharField(max_length=100)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=100)),
                ("post_code", models.CharField(max_length=20)),
                (
                    "escrow_customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("webhook_url", models.URLField(blank=True, null=True)),
                (
                    "disbursement_methods",
                    models.ManyToManyField(
                        related_name="customers", to="escrowapp.disbursementmethod"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="disbursementmethod",
            name="escrow_customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="escrowapp.escrowcustomer",
            ),
        ),
        migrations.CreateModel(
            name="EscrowTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payee_phone", models.CharField(max_length=15)),
                ("payee_email", models.EmailField(max_length=254)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_escrow", "In Escrow"),
                            ("released", "Released"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("escrow_account_id", models.CharField(max_length=50)),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegisterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=30, verbose_name="Password")),
                ("password2", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("payer_customer", models.EmailField(max_length=254)),
                ("beneficiary_customer", models.EmailField(max_length=254)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="escrowapp.item",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="escrowapp.transaction",
            ),
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("buyer", "Buyer"),
                            ("seller", "Seller"),
                            ("broker", "Broker"),
                            ("partner", "Partner"),
                        ],
                        max_length=10,
                    ),
                ),
                ("customer", models.EmailField(max_length=254)),
                ("privacy", models.BooleanField(default=False)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="escrowapp.transaction",
                    ),
                ),
            ],
            options={
                "unique_together": {("transaction", "role", "customer")},
            },
        ),
    ]
